development:
  adapter: postgresql
  encoding: unicode
  database: MtaSms_development
  pool: 5
  username: Lopez
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: MtaSms_test
  pool: 5
  username: Lopez
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: MtaSms_production
  pool: 5
  username: Lopez
  password:
